// GENERATED by scripts/site-media.mjs — do not edit. Refresh with `pnpm site:media`.
export const siteMedia = {
	exportedAt: "2026-07-21T23:12:59.415Z",
	captures: {
		authoring: {
			file: "authoring.png",
			journey: "saved-workflows",
			title: "Inspect a saved DataTable"
		},
		audit: {
			file: "audit.png",
			journey: "saved-workflows",
			title: "Review texture evidence"
		},
		gameText: {
			file: "game-text.png",
			journey: "saved-workflows",
			title: "Search the saved game text corpus"
		},
		mapReview: {
			file: "map-review.png",
			journey: "map-review",
			title: "Review before and after"
		}
	},
	journeys: {
		"saved-workflows": {
			recordingId: "20260715110016907-saved-workflows-c45c284f",
			commit: "87ea404",
			dirty: true,
			finishedAt: "2026-07-15T11:00:35.031Z",
			video: "saved-workflows.webm"
		},
		"map-review": {
			recordingId: "20260715112437100-map-review-abea8221",
			commit: "87ea404",
			dirty: true,
			finishedAt: "2026-07-15T11:24:58.226Z",
			video: "map-review.webm"
		}
	}
} as const;
